"""
Django settings for GESTION_CORRESPONDENCIA project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR=os.path.dirname(os.path.dirname(os.path.abspath(__file__))) #-------------------------------


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+r2bzw&5dv!aqw7#iklm$(_-8x)%6v9ck-ml8!=qoy$82mrfnl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] #PERMITIR QUE CUALQUIER HOST SE CONECTE


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', #==============AGREGAR REST-FRAMEWORK===================
    'USER_APP',
    'REGISTROS_APP', #==========AGREGAR LA APP DE LOS REGISTROS===============
    'rest_framework_simplejwt',
    'rest_framework.authtoken', #===============AGREGAR JWT===================
    'corsheaders',  # PARA DESACTIVAR LOS "CORS HEADERS"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'GESTION_CORRESPONDENCIA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GESTION_CORRESPONDENCIA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd9ktj65smu08t5',
        'USER': 'zjraorfaxpiidr',
        'PASSWORD': '7df40e1bdb14e2f1aafbf1ecdeddfc0d94edf3fb928243db97b3a43b4fd30b24',
        'HOST': 'ec2-44-206-11-200.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT=os.path.join(BASE_DIR, 'staticfiles') #------------------------------------------
STATICFILES_STORAGE='whitenoise.storage.CompressedStaticFilesStorage' #----------------------------

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#-----------------------------MODIFICAR MODELO DE "USUARIO"----------------------------------
AUTH_USER_MODEL = 'USER_APP.User'


#=========================AUTENTICACIÓN POT MEDIO DE UN TOKEN=========================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ROTATE_REFRESH_TOKENS': True, #COMO LOS "TOKEN" CADUCAN CADA 5 MINUTOS, CADA QUE CADUQUE UNO, NOS VA A MANDAR UNO NUEVO
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
}

#-------------------------------------DESACTIVAR CORS HEADER---------------------------------

CORS_ORIGIN_ALLOW_ALL = True #====== DAR ACCESO A TODOS LAS URL

#-------------------------CONFIGURAR BASE DE DATOS DE PRODUCCIÓN Y DESARROLLO---------------------------------
try:
    from .local_settings import DATABASES, DEBUG
except ImportError as e:
    print('Error:', e.msg)