# Generated by Django 4.0.6 on 2022-08-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=110, verbose_name='Tipo de Servicio')),
                ('remitente', models.CharField(max_length=110, verbose_name='Remitente')),
                ('adscripcion', models.CharField(max_length=110, verbose_name='Adscripción')),
                ('razon_social', models.CharField(max_length=110, verbose_name='Razón Social')),
                ('oficio', models.CharField(max_length=110, verbose_name='Oficio')),
                ('destinatario', models.CharField(max_length=110, verbose_name='Destinatario')),
                ('num_sepomex', models.CharField(blank=True, max_length=110, null=True, verbose_name='Número de SEPOMEX')),
                ('estado', models.CharField(max_length=110, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=110, verbose_name='Municipio')),
                ('colonia', models.CharField(max_length=110, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=110, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=110, verbose_name='Número Exterior')),
                ('num_int', models.CharField(blank=True, max_length=110, null=True, verbose_name='Número Interior')),
                ('tipo_usuario', models.CharField(max_length=110, verbose_name='Tipo de Usuario')),
                ('asunto', models.CharField(max_length=110, verbose_name='Asunto')),
                ('vicepresidencia', models.CharField(max_length=110, verbose_name='Vicepresidencia')),
                ('peso', models.FloatField(blank=True, max_length=110, null=True, verbose_name='Peso')),
                ('costo', models.FloatField(blank=True, max_length=110, null=True, verbose_name='Costo')),
                ('folio_diario', models.FloatField(blank=True, max_length=110, null=True, verbose_name='Folio Diario')),
                ('folio_ms', models.CharField(max_length=110, verbose_name='Folio MS')),
                ('acuse', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_ms', models.FloatField(max_length=110, verbose_name='Folio MS')),
                ('validado', models.BooleanField(blank=True, null=True, verbose_name='Validado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('registro', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGISTROS_APP.registrostable', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Validaciones',
                'verbose_name_plural': 'Validaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
