# Generated by Django 4.0.6 on 2022-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REGISTROS_APP', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrostable',
            name='acuse',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='registrostable',
            name='costo',
            field=models.FloatField(max_length=110, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='registrostable',
            name='folio_diario',
            field=models.FloatField(max_length=110, null=True, verbose_name='Folio Diario'),
        ),
        migrations.AlterField(
            model_name='registrostable',
            name='num_sepomex',
            field=models.CharField(max_length=110, null=True, verbose_name='Número de SEPOMEX'),
        ),
        migrations.AlterField(
            model_name='registrostable',
            name='peso',
            field=models.FloatField(max_length=110, null=True, verbose_name='Peso'),
        ),
    ]
