# Generated by Django 4.0.6 on 2022-08-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REGISTROS_APP', '0003_alter_registrostable_acuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacionestable',
            name='validado',
            field=models.BooleanField(null=True, verbose_name='Validado'),
        ),
    ]
