# Generated by Django 4.0.6 on 2022-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REGISTROS_APP', '0005_alter_registrostable_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrostable',
            name='acuse',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
