# Generated by Django 4.0.6 on 2022-08-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REGISTROS_APP', '0006_alter_registrostable_acuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrostable',
            name='num_int',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Número Interior'),
        ),
    ]
